#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Ignacio_v1.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/CountdownTimer.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/Ani.jar:$APPDIR/lib/io.jar:$APPDIR/lib/dmxP512.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar" Ignacio_v1 "$@"
